In [6]:
import torch
model, transforms = torch.hub.load('harvard-visionlab/lrm-steering', 'alexnet_lrm3', pretrained=True, steering=False, force_reload=True)
print(model)

Downloading: "https://github.com/harvard-visionlab/lrm-steering/zipball/main" to /n/alvarez_lab_tier1/Lab/cache/torch/hub/main.zip


==> Loading weights for alexnet_lrm3, hash_id=63ab1b3b06
https://s3.us-east-1.wasabisys.com/visionlab-projects/dnn_feedback_dev/logs/set15/set15_alexnet_torchvision_imagenet1k_lrm_3back_2steps/28453e80-c5e5-4d76-bc81-99c5fade39ff/set15_alexnet_torchvision_imagenet1k_lrm_3back_2steps_final_weights-63ab1b3b06.pth
local_filename: /n/alvarez_lab_tier1/Lab/cache/torch/hub/set15_alexnet_torchvision_imagenet1k_lrm_3back_2steps_final_weights-63ab1b3b06.pth
<All keys matched successfully>
LRMNet(
  (feedforward): AlexNet(
    (features): Sequential(
      (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
      (1): ReLU()
      (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
      (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
      (4): ReLU()
      (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
      (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (7):

In [13]:
import torch
model.eval()
x = torch.rand(10,3,224,224)

In [14]:
with torch.no_grad():
    out = model(x, forward_passes=1)
len(out)   
out[0]

tensor([[-1.2403,  0.6444,  2.1112,  ..., -0.4410, -0.4032, -0.4524],
        [-1.0969,  0.4178,  1.8896,  ..., -0.4534, -0.7122, -0.8312],
        [-1.1433,  0.5999,  2.0798,  ..., -0.4515, -0.6131, -0.8496],
        ...,
        [-1.1844,  0.5734,  1.9856,  ..., -0.3310, -0.1186, -0.7900],
        [-0.9280,  0.5157,  2.1720,  ..., -0.3788, -0.5476, -0.8095],
        [-1.2469,  0.5101,  1.9878,  ..., -0.4985, -0.5355, -0.3992]])

In [15]:
with torch.no_grad():
    out = model(x, forward_passes=1)
len(out)   
out[0]

tensor([[-1.2403,  0.6444,  2.1112,  ..., -0.4410, -0.4032, -0.4524],
        [-1.0969,  0.4178,  1.8896,  ..., -0.4534, -0.7122, -0.8312],
        [-1.1433,  0.5999,  2.0798,  ..., -0.4515, -0.6131, -0.8496],
        ...,
        [-1.1844,  0.5734,  1.9856,  ..., -0.3310, -0.1186, -0.7900],
        [-0.9280,  0.5157,  2.1720,  ..., -0.3788, -0.5476, -0.8095],
        [-1.2469,  0.5101,  1.9878,  ..., -0.4985, -0.5355, -0.3992]])

In [16]:
with torch.no_grad():
    out = model(x, forward_passes=2)
len(out)   
out[0]

tensor([[-1.2403,  0.6444,  2.1112,  ..., -0.4410, -0.4032, -0.4524],
        [-1.0969,  0.4178,  1.8896,  ..., -0.4534, -0.7122, -0.8312],
        [-1.1433,  0.5999,  2.0798,  ..., -0.4515, -0.6131, -0.8496],
        ...,
        [-1.1844,  0.5734,  1.9856,  ..., -0.3310, -0.1186, -0.7900],
        [-0.9280,  0.5157,  2.1720,  ..., -0.3788, -0.5476, -0.8095],
        [-1.2469,  0.5101,  1.9878,  ..., -0.4985, -0.5355, -0.3992]])

In [17]:
out[1]

tensor([[-0.7497,  0.3781,  2.0520,  ..., -0.1933, -1.2317, -0.6173],
        [-0.3226,  0.3404,  1.8778,  ..., -0.1909, -1.5044, -0.6404],
        [-0.6053,  0.4258,  1.9751,  ...,  0.0723, -1.2615, -0.8122],
        ...,
        [-0.6668,  0.3714,  1.9055,  ...,  0.2147, -1.0289, -0.8298],
        [-0.5214,  0.2333,  1.9206,  ...,  0.0031, -1.2414, -0.7742],
        [-0.7068,  0.3681,  1.9491,  ...,  0.0496, -1.1576, -0.7089]])

In [27]:
import torch.nn as nn

class ModelWrapper(nn.Module):
    def __init__(self, model, forward_passes=2):
        super(ModelWrapper, self).__init__() 
        self.model = model
        self.forward_passes = forward_passes
    
    def forward(self, x):
        out = self.model(x, forward_passes=self.forward_passes)
        print(len(out))
        return out[-1]

In [30]:
lrm, transforms = torch.hub.load('harvard-visionlab/lrm-steering', 'alexnet_lrm3', pretrained=True, steering=False, force_reload=False)
model = ModelWrapper(lrm, forward_passes=2)
model

Using cache found in /n/alvarez_lab_tier1/Lab/cache/torch/hub/harvard-visionlab_lrm-steering_main


==> Loading weights for alexnet_lrm3, hash_id=63ab1b3b06
https://s3.us-east-1.wasabisys.com/visionlab-projects/dnn_feedback_dev/logs/set15/set15_alexnet_torchvision_imagenet1k_lrm_3back_2steps/28453e80-c5e5-4d76-bc81-99c5fade39ff/set15_alexnet_torchvision_imagenet1k_lrm_3back_2steps_final_weights-63ab1b3b06.pth
local_filename: /n/alvarez_lab_tier1/Lab/cache/torch/hub/set15_alexnet_torchvision_imagenet1k_lrm_3back_2steps_final_weights-63ab1b3b06.pth
<All keys matched successfully>


ModelWrapper(
  (model): LRMNet(
    (feedforward): AlexNet(
      (features): Sequential(
        (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
        (1): ReLU()
        (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
        (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
        (4): ReLU()
        (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
        (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (7): ReLU()
        (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (9): ReLU()
        (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (11): ReLU()
        (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
      )
      (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
      (classifier): Sequential(
        (0): Dropout(p=0.5, inplace=False)
 

In [32]:
x = torch.rand(10, 3, 224, 224)
with torch.no_grad():
    out = model(x)
out.shape

2


torch.Size([10, 1000])